services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - "100.64.79.123:4005:80"
    volumes:
      - /mnt/dietpi_userdata:/srv
      - ./database:/database
      - ./config:/config

